### ISSUE TITLE
Issue with setup.py opening README.rst containing utf-8 characters

### ISSUE THREAD

**Issue by gcurchod** [spinus/sphinxcontrib-images#45]
Character "horizontal ellipsis" (…) is used in [README.rst](https://github.com/spinus/sphinxcontrib-images/blob/master/README.rst). This file is opened and read in [setup.py](https://github.com/spinus/sphinxcontrib-images/blob/master/setup.py#L34) but returns the following error while trying to `pip install git+https://github.com/spinus/sphinxcontrib-images`
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ie71f1fg-build/setup.py", line 34, in <module>
        long_description=open('README.rst').read(),
      File "/mnt/ed/ct/lnx/rh/53/64/python/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1481: ordinal not in range(128)
```
Using _Python 3.5.2 :: Anaconda 4.3.0 (64-bit)_
As solution could be to open the file [README.rst](https://github.com/spinus/sphinxcontrib-images/blob/master/README.rst) with explicite encoding as proposed in the following patch:
```diff
From d6a79557877d8ed523cf759bc45f8424820a2a87 Mon Sep 17 00:00:00 2001
From: Gilles Curchod <https://github.com/gcurchod>
Date: Thu, 28 Sep 2017 10:59:06 +0200
Subject: [PATCH] implicite utf-8 encoding while opening README.rst since it
 uses utf-8 characters

---
 setup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/setup.py b/setup.py
index 3ea3ef8..dd9e99b 100755
--- a/setup.py
+++ b/setup.py
@@ -31,7 +31,7 @@ setup(
     author=u'Tomasz Czy\u017c',
     author_email='tomasz.czyz@gmail.com',
     description='Sphinx "images" extension',
-    long_description=open('README.rst').read(),
+    long_description=open('README.rst', encoding="utf-8").read(),
     zip_safe=False,
     classifiers=[
         'Development Status :: 4 - Beta',
-- 
2.11.0
```

**Comment by spinus** [comment]
@gcurchod I think that should be fixed, would you confirm?
